# Change these first
owner: punokawan # Your GitHub username
repo: uptime_website_unj # Your GitHub repository name

# Add your sites here
sites:
  # - name: Google
  #   url: https://www.google.com
  #   __dangerous__body_down: "File not found"
  - name: UNJ
    url: http://unj.ac.id
  - name: SIAKAD UNJ
    url: http://siakad.unj.ac.id
  - name: SIUKAT UNJ
    url: http://siukat.unj.ac.id
  - name: Aplikasi Peserta PSB
    url: http://103.8.12.221/login
  - name: Aplikasi Admin PSB service
    url: http://103.8.12.221:3000/
  - name: Aplikasi SIMAMA POLTEKES FE
    url: http://103.74.143.73/
  - name: Aplikasi SIMAMA POLTEKES BE
    url: http://103.74.143.73:3000/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: punokawan.github.io/uptime_website_unj
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime_website_unj
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No website required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /uptime_website_unj
    - title: GitHub
      href: github.com/punokawan/uptime_website_unj.git

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
